apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: golist

resources:
- github.com/araghav091/golist-frontend/deploy
- golist-frontend-ingress.yaml

patches:
- patch: |-
    - op: replace
      path: /data/config.json
      value: '{"api": "http://127.0.0.1:8080/api/products"}'
  target:
    kind: ConfigMap
    name: golist-frontend-config
    version: v1
