apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: golist

resources:
- github.com/araghav091/golist-api/deploy
- golist-api-ingress.yaml

patches:
- patch: |-
    - op: replace
      path: /data/config.json
      value: '{"connection_string":"golist:golist@tcp(golist-db-mariadb:3306)/golist","port":8080}'
  target:
    kind: ConfigMap
    name: golist-api-config
    version: v1
